version: '3.5'

services:

  project:
    container_name: hackathon_selection
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8888:8888
    volumes:
      - '.:/hackathon_selection'
